## Настройки Hibernate/JPA
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.sql.init.mode=always
#hibernate.show_sql=true
#hibernate.jdbc.time_zone=UTC
#
## Логирование
#logging.level.org.springframework.orm.jpa=INFO
#logging.level.org.springframework.transaction=INFO
#logging.level.org.springframework.transaction.interceptor=TRACE
#logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
#
## Профиль
#spring.config.activate.on-profile=default
#
## Настройки H2 (заменяем PostgreSQL)
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:shareit;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#spring.datasource.username=sa
#spring.datasource.password=
#
## Дополнительные настройки H2 (опционально)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


spring:
  application:
    name: shareit

  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: sa
    password: "1"               # пароль в кавычках, особенно если содержит спецсимволы
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000     # таймаут соединения
      maximum-pool-size: 10         # максимальный размер пула соединений

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none                # отключает любые автоматические действия со стороны Hibernate
    #      ddl-auto: validate           # проверить совпадают ли структура БД и сущности
    properties:
      hibernate:
        show_sql: true              # включить вывод SQL-запросов, генерируемых Hibernate, в логи приложения
        format_sql: true            # форматирует выводимый SQL перед тем, как он попадает в логи

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE